
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    welcome: "Welcome to Zaza-Wake AI",
    onboardingDesc: "We help you wake up fresh using privacy-focused AI verification.",
    selectLanguage: "Select Language",
    setSleepTime: "When do you go to bed?",
    setWakeTime: "When do you wake up?",
    doYouNap: "Do you take a nap during the day?",
    whenNap: "When do you take the nap?",
    yes: "Yes",
    no: "No",
    setBackToSleepTime: "Daily Nap Alarm (Optional)",
    backToSleepDesc: "A fixed daily alarm for your afternoon nap or second sleep.",
    getStarted: "Get Started",
    nextAlarm: "Next Alarm",
    bedTime: "Bed Time",
    wakeUpTime: "Wake-Up Time",
    backToSleep: "Nap Alarm",
    sleepingNow: "Sleep Mode Active",
    awakeCheck: "Analyzing Face...",
    awakeConfirmed: "Awake! Good Morning",
    stats: "Sleep Stats",
    responseTime: "Response Time",
    avgWakeSpeed: "Avg. Wake Speed",
    settings: "Settings",
    cameraPermission: "Camera access required for wake verification",
    startSleep: "Go to Sleep",
    stopAlarm: "Stop Alarm",
    languageToggle: "العربية",
    napTimer: "Quick Timer",
    addTimer: "New Timer",
    startNap: "Start Session",
    cancelTimer: "Cancel",
    napInProgress: "Nap in Progress",
    min: "min",
    testAlarm: "Test Alarm",
    testDesc: "Try the alarm verification immediately.",
    itsBedtime: "It's Bedtime!",
    bedtimeDesc: "Time to rest and recharge for tomorrow.",
    dismiss: "Dismiss",
    alarmSound: "Alarm Sound",
    zazaVoice: "Zaza's Voice",
    soundClassic: "Classic",
    soundBell: "Bell",
    soundDigital: "Digital",
    activateVoice: "Activate Zaza's Voice",
    voiceReady: "Voice Engine Ready",
    voiceRequired: "Activation Required",
    voiceDesc: "To hear Zaza's voice, click below to link your Google service. It takes 5 seconds!",
    billingLink: "Learn more about setup",
    addReminder: "Add Reminder",
    reminderLabel: "What is it for?",
    reminderTime: "Reminder Time",
    studyTime: "Study",
    gymTime: "Gym",
    workTime: "Work",
    save: "Save",
    reminders: "Reminders",
    noReminders: "No reminders set",
    itIsTimeFor: "It is time for "
  },
  ar: {
    welcome: "مرحباً بك في Zaza-Wake AI",
    onboardingDesc: "نساعدك على الاستيقاظ بنشاط باستخدام التحقق بالذكاء الاصطناعي مع الحفاظ على خصوصيتك.",
    selectLanguage: "اختر اللغة",
    setSleepTime: "متى تذهب للنوم عادةً؟",
    setWakeTime: "متى تستيقظ صباحاً؟",
    doYouNap: "هل تأخذ قيلولة خلال النهار؟",
    whenNap: "متى تأخذ القيلولة؟",
    yes: "نعم",
    no: "لا",
    setBackToSleepTime: "منبه القيلولة اليومي (اختياري)",
    backToSleepDesc: "منبه ثابت يومياً لوقت القيلولة لضمان استيقاظك وعدم إطالة النوم.",
    getStarted: "ابدأ الآن",
    nextAlarm: "المنبه القادم",
    bedTime: "وقت النوم",
    wakeUpTime: "وقت الاستيقاظ",
    backToSleep: "منبه القيلولة",
    sleepingNow: "وضع النوم نشط",
    awakeCheck: "تحليل الوجه...",
    awakeConfirmed: "تم التأكيد! صباح الخير",
    stats: "إحصائيات النوم",
    responseTime: "وقت الاستجابة",
    avgWakeSpeed: "متوسط سرعة الاستيقاظ",
    settings: "الإعدادات",
    cameraPermission: "مطلوب الوصول للكاميرا للتحقق من الاستيقاظ",
    startSleep: "اذهب للنوم",
    stopAlarm: "إيقاف المنبه",
    languageToggle: "English",
    napTimer: "مؤقت سريع",
    addTimer: "مؤقت جديد",
    startNap: "ابدأ الجلسة",
    cancelTimer: "إلغاء",
    napInProgress: "القيلولة جارية",
    min: "دقيقة",
    testAlarm: "تجربة المنبه",
    testDesc: "جرب التحقق من المنبه على الفور.",
    itsBedtime: "حان وقت النوم!",
    bedtimeDesc: "وقت الراحة واستعادة النشاط للغد.",
    dismiss: "تجاهل",
    alarmSound: "صوت المنبه",
    zazaVoice: "صوت زازا",
    soundClassic: "كلاسيك",
    soundBell: "جرس",
    soundDigital: "رقمي",
    activateVoice: "تفعيل صوت زازا",
    voiceReady: "محرك الصوت جاهز",
    voiceRequired: "مطلوب التفعيل",
    voiceDesc: "لسماع صوت زازا بوضوح، يرجى الضغط على الزر أدناه لربط الخدمة (تستغرق 5 ثوانٍ فقط).",
    billingLink: "تعرف على طريقة الإعداد",
    addReminder: "إضافة تذكير",
    reminderLabel: "بماذا تريد أن أذكرك؟",
    reminderTime: "وقت التذكير",
    studyTime: "دراسة",
    gymTime: "نادي رياضي",
    workTime: "عمل",
    save: "حفظ",
    reminders: "التذكيرات",
    noReminders: "لا توجد تذكيرات",
    itIsTimeFor: "حان وقت الـ "
  }
};

export const OPTIMAL_SLEEP_DURATION = 8; // Hours
